# Generated by Django 5.0.2 on 2024-08-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='auction_pictures/default-avatar1', upload_to='auction_pictures/'),
        ),
    ]
