# Generated by Django 5.0.2 on 2024-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='auction_pictures/avatars/default-avatar1.png', upload_to='auction_pictures/avatars/'),
        ),
    ]
