# Generated by Django 5.0.2 on 2024-07-30 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reveal_identity', models.BooleanField(default=True)),
                ('legal_responsibility', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_pictures/')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='auctions.auction')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='auctions.auction')),
            ],
        ),
    ]
