# Generated by Django 5.0.2 on 2024-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_current_bid_auction_current_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
