# Generated by Django 5.0.2 on 2024-08-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
