# Generated by Django 5.0.2 on 2024-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_location_latitude_auction_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
